name: Build and deploy container to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  RESOURCE_GROUP: bobby-b-bot

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    
    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infra and container
      run: |
        az container create \
          --name bobby-b-bot \
          -g ${{ env.RESOURCE_GROUP }}
          --image ghcr.io/${{ env.REPO }}:${{ github.sha }} \
          --cpu 0.5 \
          --memory 0.5 \
          -e "ENV=PRODUCTION TOKEN=${{ secrets.token }}""
